wordlist:
	edictor wordlist --name=opp-full --data=../cldf/cldf-metadata.json --addon="cognacy:cogid","alignment:alignment"

wordlist-auto:
	edictor wordlist --name=opp-auto --data=../cldf/cldf-metadata.json --preprocessing=autocogid.py --addon="cognacy:cogid","cogids:cogids","alignment:alignment"
